url: "http://www.westhousehotelnewyork.com"

# Build settings    
default_lang: 'en'
languages: ['en']

exclude: ['sitemap.json']
keep_files: ['assets']
rsync_copy: ['_assets']

page_gen:
  - data: 'events'
    template: 'tmp-calendar-more'
    dir: 'calendar-more'
  - data: 'blog'
    template: 'tmp-blog-more'
    dir: 'blog-details'
